name: osm_nominatim
description: A library to perform OSM Nominatim searches also supporting reverse searches
version: 1.0.0
homepage: https://github.com/jld3103/osm-nominatim

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  http: ">=0.12.0 <0.13.0"
